version: '3'
services:
  api:
    image: node:12.18.4
    working_dir: /code
    volumes:
      - type: bind
        source: ./express-api
        target: /code
        
  db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=trabbit
    
