services:
  client:
    container_name: trabbit_dev_client
    build: ./client
    image: trabbit_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: trabbit_dev_api
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=habits
      - DB_CONNECTION=mongodb://habits:corgie@db:27017
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: trabbit_dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=trabbit
      - MONGO_INITDB_DATABASE=habits
      - MONGO_INITDB_ROOT_PASSWORD=corgie
volumes:
  dbdata:
networks: 
  default:
    name: trabbit_api
